In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [2]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [6]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [15]:
from numpy import random

#Generate a random integer from 0 to 100:
x = random.randint(100)
print(x)
print("-")

# Define the range
lower_bound = 1
upper_bound = 100

# Generate 5 random integers within the range
random_integers = np.random.randint(lower_bound, upper_bound + 1, size=5)

print("Random integers:", random_integers)

2
-
Random integers: [39 30 32 70 30]


In [14]:
# Generate a random float from 0 to 1:
x = random.rand()
print(x)
print("-")

#Generate a 1-D array containing 5 random floats:
x = random.rand(5)
print(x)      

0.41930549783237836
-
[0.14918863 0.34344053 0.63522142 0.05235805 0.1936798 ]


In [16]:
x = random.choice([3, 5, 7, 9])
print(x)

7


In [4]:
#Book Management

class Library:
    def __init__(self):
        self.books = []
        self.borrowed_books = []

    def add_book(self, title):
        self.books.append(title)
        print(f"Book '{title}' added to the library.")

    def borrow_book(self, title):
        if title in self.books:
            self.books.remove(title)
            self.borrowed_books.append(title)
            print(f"Book '{title}' borrowed.")
        else:
            print(f"Book '{title}' is not available.")

    def return_book(self, title):
        if title in self.borrowed_books:
            self.borrowed_books.remove(title)
            self.books.append(title)
            print(f"Book '{title}' returned.")
        else:
            print(f"Book '{title}' was not borrowed.")

    def list_books(self):
        print("Available books:")
        for book in self.books:
            print(book)

library = Library()
while True:
    print("\nOptions: add, borrow, return, list, exit")
    action = input("Enter action: ").strip().lower()

    if action == "add":
        title = input("Enter book title to add: ")
        library.add_book(title)
    elif action == "borrow":
        title = input("Enter book title to borrow: ")
        library.borrow_book(title)
    elif action == "return":
        title = input("Enter book title to return: ")
        library.return_book(title)
    elif action == "list":
        library.list_books()
    elif action == "exit":
        print("Exiting...")
        break
    else:
        print("Invalid action.")



Options: add, borrow, return, list, exit


Enter action:  add
Enter book title to add:  Hello World


Book 'Hello World' added to the library.

Options: add, borrow, return, list, exit


Enter action:  list


Available books:
Hello World

Options: add, borrow, return, list, exit


Enter action:  borrow
Enter book title to borrow:  Hello World


Book 'Hello World' borrowed.

Options: add, borrow, return, list, exit


Enter action:  list


Available books:

Options: add, borrow, return, list, exit


Enter action:  return
Enter book title to return:  Hello World2


Book 'Hello World2' was not borrowed.

Options: add, borrow, return, list, exit


Enter action:  Hello World


Invalid action.

Options: add, borrow, return, list, exit


Enter action:  return
Enter book title to return:  Hello World


Book 'Hello World' returned.

Options: add, borrow, return, list, exit


Enter action:  list


Available books:
Hello World

Options: add, borrow, return, list, exit


Enter action:  exit


Exiting...


In [3]:
#TodoList

class TodoList:
    def __init__(self):
        self.tasks = []

    def add_task(self, description):
        self.tasks.append({"description": description, "completed": False})
        print(f"Task '{description}' added.")

    def complete_task(self, index):
        if 0 <= index < len(self.tasks):
            self.tasks[index]["completed"] = True
            print(f"Task '{self.tasks[index]['description']}' marked as complete.")
        else:
            print("Invalid task index.")

    def view_tasks(self):
        print("To-Do List:")
        for i, task in enumerate(self.tasks):
            status = "Completed" if task["completed"] else "Incomplete"
            print(f"{i}. {task['description']} - {status}")

todo_list = TodoList()
while True:
    print("\nOptions: add, complete, view, exit")
    action = input("Enter action: ").strip().lower()

    if action == "add":
        description = input("Enter task description: ")
        todo_list.add_task(description)
    elif action == "complete":
        index = int(input("Enter task index to complete: "))
        todo_list.complete_task(index)
    elif action == "view":
        todo_list.view_tasks()
    elif action == "exit":
        print("Exiting...")
        break
    else:
        print("Invalid action.")



Options: add, complete, view, exit


Enter action:  add
Enter task description:  Sleep


Task 'Sleep' added.

Options: add, complete, view, exit


Enter action:  view


To-Do List:
0. Sleep - Incomplete

Options: add, complete, view, exit


Enter action:  add
Enter task description:  eat


Task 'eat' added.

Options: add, complete, view, exit


Enter action:  complete
Enter task index to complete:  1


Task 'eat' marked as complete.

Options: add, complete, view, exit


Enter action:  view


To-Do List:
0. Sleep - Incomplete
1. eat - Completed

Options: add, complete, view, exit


Enter action:  exit


Exiting...


In [2]:
import random

class Robot:
    def __init__(self, name):
        self.name = name
        self.x = 0  # Random initial position on 4x4 grid
        self.y = 0
        self.is_destroyed = False

    def move(self):
        direction = random.choice(['up', 'down', 'left', 'right'])
        if direction == 'up' and self.y < 3:
            self.y += 1
        elif direction == 'down' and self.y > 0:
            self.y -= 1
        elif direction == 'left' and self.x > 0:
            self.x -= 1
        elif direction == 'right' and self.x < 3:
            self.x += 1

    def position(self):
        return (self.x, self.y)

    def battle(self, other_robot):
        if self.position() == other_robot.position():
            self_number = random.randint(1, 10)
            other_number = random.randint(1, 10)
            print(f"{self.name} vs {other_robot.name}:")
            print(f"{self.name} rolls {self_number}, {other_robot.name} rolls {other_number}")
            if self_number > other_number:
                print(f"{self.name} wins!")
                other_robot.is_destroyed = True
            elif other_number > self_number:
                print(f"{other_robot.name} wins!")
                self.is_destroyed = True
            else:
                print("It's a tie!")
    
    def is_active(self):
        return not self.is_destroyed


# Initialize robots
robotA = Robot("Robot A")
robotB = Robot("Robot B")

# Game loop
while robotA.is_active() and robotB.is_active():
    print("\nCurrent Positions:")
    print(f"{robotA.name}: {robotA.position()}")
    print(f"{robotB.name}: {robotB.position()}")

    # Robots move
    robotA.move()
    robotB.move()

    # Check if they battle
    robotA.battle(robotB)

# Game over
if robotA.is_active():
    print(f"\n{robotA.name} wins! {robotB.name} is destroyed.")
else:
    print(f"\n{robotB.name} wins! {robotA.name} is destroyed.")



Current Positions:
Robot A: (0, 0)
Robot B: (0, 0)

Current Positions:
Robot A: (0, 1)
Robot B: (1, 0)

Current Positions:
Robot A: (0, 1)
Robot B: (0, 0)

Current Positions:
Robot A: (0, 1)
Robot B: (0, 0)

Current Positions:
Robot A: (1, 1)
Robot B: (0, 0)

Current Positions:
Robot A: (1, 2)
Robot B: (0, 1)
Robot A vs Robot B:
Robot A rolls 3, Robot B rolls 10
Robot B wins!

Robot B wins! Robot A is destroyed.


In [6]:
obstacles = [(0, 3), (1, 1), (2, 2)]

print(type(obstacles))
print(type(obstacles[0]))

<class 'list'>
<class 'tuple'>


In [7]:
import random

class Robot:
    def __init__(self, name, start, goal, obstacles):
        self.name = name
        self.start = start
        self.goal = goal
        self.obstacles = obstacles
        self.path = []
    
    def move(self, direction):
        x, y = self.path[-1] if self.path else self.start
        if direction == 'up' and y < 3:
            y += 1
        elif direction == 'down' and y > 0:
            y -= 1
        elif direction == 'left' and x > 0:
            x -= 1
        elif direction == 'right' and x < 3:
            x += 1
        return (x, y)
    
    def generate_path(self):
        current = self.start
        self.path.append(current)
        while current != self.goal:
            possible_moves = []
            if current[0] > 0:
                possible_moves.append('left')
            if current[0] < 3:
                possible_moves.append('right')
            if current[1] > 0:
                possible_moves.append('down')
            if current[1] < 3:
                possible_moves.append('up')
            
            # Avoid obstacles and previously visited cells
            possible_moves = [move for move in possible_moves if self.move(move) not in self.obstacles and self.move(move) not in self.path]
            
            if not possible_moves:
                return False
            move = random.choice(possible_moves)
            current = self.move(move)
            self.path.append(current)
        
        return True

# Initialize grid and obstacles
grid_size = 4
obstacles = [(0, 3), (1, 1), (2, 2)]
robotA = Robot("Robot A", (0, 0), (3, 3), obstacles)

# Generate paths for robots
robotA.generate_path()

# Display initial grid
print("Initial grid:")
for y in range(grid_size):
    print("---------------------")
    for x in range(grid_size):
        if (x, y) == robotA.start:
            print(f"| R ", end='')
        elif (x, y) == robotA.goal:
            print(f"| {grid_size * grid_size - 1} ", end='')
        elif (x, y) in obstacles:
            print(f"| X ", end='')
        else:
            print(f"|   ", end='')
    print(f"|")
print("---------------------")

# Display path taken by the robot
print("\nPath taken by the robot:")
for y in range(grid_size):
    print("---------------------")
    for x in range(grid_size):
        if (x, y) == robotA.start:
            print(f"| R ", end='')
        elif (x, y) in robotA.path:
            print(f"| → ", end='')
        elif (x, y) == robotA.goal:
            print(f"| {grid_size * grid_size - 1} ", end='')
        elif (x, y) in obstacles:
            print(f"| X ", end='')
        else:
            print(f"|   ", end='')
    print(f"|")
print("---------------------")

# Display final path
print("\nFinal path:")
print(f"({robotA.name} starts at {robotA.start})")
for i, pos in enumerate(robotA.path):
    if i == len(robotA.path) - 1:
        print(f"{robotA.name} reaches {pos} ({grid_size * grid_size - 1})")
    else:
        print(f"→ {pos}", end=' ')


Initial grid:
---------------------
| R |   |   |   |
---------------------
|   | X |   |   |
---------------------
|   |   | X |   |
---------------------
| X |   |   | 15 |
---------------------

Path taken by the robot:
---------------------
| R |   |   |   |
---------------------
| → | X |   |   |
---------------------
| → | → | X |   |
---------------------
| X | → | → | → |
---------------------

Final path:
(Robot A starts at (0, 0))
→ (0, 0) → (0, 1) → (0, 2) → (1, 2) → (1, 3) → (2, 3) Robot A reaches (3, 3) (15)


In [8]:
import random

class Robot:
    def __init__(self, name, start, goal, obstacles):
        self.name = name
        self.start = start
        self.goal = goal
        self.obstacles = obstacles
        self.path = []
    
    def move(self, direction):
        x, y = self.path[-1] if self.path else self.start
        if direction == 'up' and y < 3:
            y += 1
        elif direction == 'down' and y > 0:
            y -= 1
        elif direction == 'left' and x > 0:
            x -= 1
        elif direction == 'right' and x < 3:
            x += 1
        return (x, y)
    
    def generate_path(self):
        current = self.start
        self.path.append(current)
        while current != self.goal:
            possible_moves = []
            if current[0] > 0:
                possible_moves.append('left')
            if current[0] < 3:
                possible_moves.append('right')
            if current[1] > 0:
                possible_moves.append('down')
            if current[1] < 3:
                possible_moves.append('up')
            
            # Avoid obstacles and previously visited cells
            possible_moves = [move for move in possible_moves if self.move(move) not in self.obstacles and self.move(move) not in self.path]
            
            if not possible_moves:
                return False
            move = random.choice(possible_moves)
            current = self.move(move)
            self.path.append(current)
        
        return True

# Initialize grid and obstacles
grid_size = 4
obstacles = [(0, 3), (1, 1), (2, 2)]
robotA = Robot("Robot A", (0, 0), (3, 3), obstacles)

# Generate paths for robots
robotA.generate_path()

# Display initial grid
print("Initial grid:")
for y in range(grid_size):
    print("---------------------")
    for x in range(grid_size):
        if (x, y) == robotA.start:
            print(f"| R ", end='')
        elif (x, y) == robotA.goal:
            print(f"| {grid_size * grid_size - 1} ", end='')
        elif (x, y) in obstacles:
            print(f"| X ", end='')
        else:
            print(f"|   ", end='')
    print(f"|")
print("---------------------")

# Display path taken by the robot
print("\nPath taken by the robot:")
for y in range(grid_size):
    print("---------------------")
    for x in range(grid_size):
        if (x, y) == robotA.start:
            print(f"| R ", end='')
        elif (x, y) in robotA.path:
            print(f"| → ", end='')
        elif (x, y) == robotA.goal:
            print(f"| {grid_size * grid_size - 1} ", end='')
        elif (x, y) in obstacles:
            print(f"| X ", end='')
        else:
            print(f"|   ", end='')
    print(f"|")
print("---------------------")

# Display final path
print("\nFinal path:")
print(f"({robotA.name} starts at {robotA.start})")
for i, pos in enumerate(robotA.path):
    if i == len(robotA.path) - 1:
        print(f"{robotA.name} reaches {pos} ({grid_size * grid_size - 1})")
    else:
        print(f"→ {pos}", end=' ')


Initial grid:
---------------------
| R |   |   |   |
---------------------
|   | X |   |   |
---------------------
|   |   | X |   |
---------------------
| X |   |   | 15 |
---------------------

Path taken by the robot:
---------------------
| R | → | → | → |
---------------------
|   | X | → | → |
---------------------
|   |   | X |   |
---------------------
| X |   |   | 15 |
---------------------

Final path:
(Robot A starts at (0, 0))
→ (0, 0) → (1, 0) → (2, 0) → (3, 0) → (3, 1) Robot A reaches (2, 1) (15)
